import { Topic, TagLevel } from './types';

export const TOPIC_CATALOG = [
  { id: 1, label: "Vi tri dia li va pham vi lanh tho", short: "VTDL-PVLT", level: TagLevel.NB, group: "Vi tri dia li & pham vi lanh tho", text: "1. VỊ TRÍ ĐỊA LÍ VÀ PHẠM VI LÃNH THỔ VIỆT NAM; 1.1 Vị trí địa lí; Vị trí:", icon: "location_on", color: "#00f5ff", mastery: 0, scale: 1.0 },
  { id: 2, label: "Anh huong vi tri dia li va pham vi lanh tho", short: "AH VTDL", level: TagLevel.TH, group: "Vi tri dia li & pham vi lanh tho", text: "- Vùng trời: là khoảng không gian bao trùm lên lãnh thổ nước ta.; 1.3 Ảnh hưởng của vị trí địa lí và phạm vi lãnh thổ đối với sự hình thành đặc điểm địa lí tự nhiên Việt Nam; * Vị trí địa lí và lãnh thổ đã quy định đặc điểm cơ bản của thiên nhiên nước ta mang tính chất nhiệt đới ẩm gió mùa, chịu ảnh hưởng sâu sắc của biển và phân hóa đa dạng:", icon: "explore", color: "#00f5ff", mastery: 0, scale: 1.0 },
  { id: 3, label: "Dac diem dia hinh Viet Nam", short: "Dia hinh VN", level: TagLevel.NB, group: "Dia hinh & khoang san", text: "- Hướng vòng cung: thể hiện rõ nhất ở vùng núi Đông Bắc.; c) Địa hình có tính chất phân bậc khá rõ rệt; - Nguyên nhân: quá trình địa chất lâu dài, vận động tạo núi Hi-ma-lay-a.", icon: "terrain", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 4, label: "Cac khu vuc dia hinh", short: "Khu vuc DH", level: TagLevel.NB, group: "Dia hinh & khoang san", text: "- Đồng bằng chiếm 1/4 diện tích lãnh thổ.; b) Địa hình có hai hướng chính là tây bắc-đông nam và hướng vòng cung; - Hướng tây bắc- đông nam như Con Voi, Hoàng Liên Sơn, Trường Sơn Bắc,...", icon: "landscape", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 5, label: "Dac diem khoang san Viet Nam", short: "Dac diem KS", level: TagLevel.TH, group: "Dia hinh & khoang san", text: "+ Đối với nông nghiệp, lâm nghiệp: trồng rừng, cây công nghiệp, cây ăn quả, chăn nuôi gia súc.; + Đối với công nghiệp: phát triển khai thác khoáng sản, luyện kim, thủy điện,...; + Đối với du lịch: Khu vực đồi núi có khí hậu mát mẻ, cảnh quan đa dạng, đặc sắc là cơ sở hình thành các điểm du lịch có giá trị.", icon: "diamond", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 6, label: "Phan bo va su dung khoang san", short: "PB-SD KS", level: TagLevel.TH, group: "Dia hinh & khoang san", text: "+ Đối với nông nghiệp, lâm nghiệp: trồng rừng, cây công nghiệp, cây ăn quả, chăn nuôi gia súc.; + Đối với công nghiệp: phát triển khai thác khoáng sản, luyện kim, thủy điện,...; + Đối với du lịch: Khu vực đồi núi có khí hậu mát mẻ, cảnh quan đa dạng, đặc sắc là cơ sở hình thành các điểm du lịch có giá trị.", icon: "precision_manufacturing", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 7, label: "Phan hoa dia hinh va tu nhien", short: "Phan hoa DH", level: TagLevel.VD, group: "Dia hinh & khoang san", text: "1.3 Ảnh hưởng của vị trí địa lí và phạm vi lãnh thổ đối với sự hình thành đặc điểm địa lí tự nhiên Việt Nam; * Vị trí địa lí và lãnh thổ đã quy định đặc điểm cơ bản của thiên nhiên nước ta mang tính chất nhiệt đới ẩm gió mùa, chịu ảnh hưởng sâu sắc của biển và phân hóa đa dạng:; - Khí hậu: một năm có 2 mùa rõ rệt, chịu ảnh hưởng của các cơn bão lớn.", icon: "layers", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 8, label: "Khi hau nhiet doi am gio mua", short: "KH NDAGM", level: TagLevel.NB, group: "Khi hau & thuy van", text: "- Cán cân bức xạ từ 70-100 kcal/cm2/năm.; b) Tính chất ẩm; - Lượng mưa trung bình năm lớn: từ 1500 - 2000 mm/năm.", icon: "thermostat", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 9, label: "Luu vuc song va he thong song lon", short: "Luu vuc song", level: TagLevel.NB, group: "Khi hau & thuy van", text: "2. THUỶ VĂN VIỆT NAM; 2.1. Sông ngòi; a) Đặc điểm chung", icon: "water", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 10, label: "Phan hoa khi hau Viet Nam", short: "Phan hoa KH", level: TagLevel.TH, group: "Khi hau & thuy van", text: "a) Phân hoá theo chiều bắc-nam; - Miền khí hậu phía Bắc: nhiệt độ trung bình năm trên 200C, có mùa đông lạnh, ít mưa; mùa hạ nóng, ẩm và mưa nhiều.; - Miền khí hậu phía Nam: nhiệt độ trung bình năm trên 250C, có 2 mùa mưa, khô phân hóa rõ rệt.", icon: "wb_sunny", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 11, label: "Tac dong bien doi khi hau toi khi hau va thuy van", short: "BDKH KH-TV", level: TagLevel.TH, group: "Khi hau & thuy van", text: "CHỦ ĐỀ 2: KHÍ HẬU VÀ THUỶ VĂN VIỆT NAM; 1. KHÍ HẬU VIỆT NAM; Khí hậu Việt Nam phân hóa thành 3 đai cao gồm: nhiệt đới gió mùa; cận nhiệt đới gió mùa trên núi và ôn đới gió mùa trên núi.", icon: "cyclone", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 12, label: "Khi hau va nong nghiep", short: "KH-Nong nghiep", level: TagLevel.TH, group: "Khi hau & thuy van", text: "c) Tính chất gió mùa; * Gió mùa mùa đông:; - Thời gian: từ tháng 11 – 4 năm sau", icon: "agriculture", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 13, label: "Phan tich mot he thong song", short: "Mot HT song", level: TagLevel.TH, group: "Khi hau & thuy van", text: "b) Một số hệ thống sông; * Hệ thống sông Hồng; - Đặc điểm mạng lưới sông:", icon: "humidity_mid", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 14, label: "Ho, dam va nuoc ngam", short: "Ho-dam-NN", level: TagLevel.TH, group: "Khi hau & thuy van", text: "- Lượng mưa trung bình năm lớn: từ 1500 - 2000 mm/năm.; - Độ ẩm không khí cao, trên 80%.; c) Tính chất gió mùa", icon: "waves", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 15, label: "Doc bieu do khi hau va tram khi tuong thuy van", short: "Doc BD KH", level: TagLevel.TH, group: "Khi hau & thuy van", text: "b) Tính chất ẩm; - Lượng mưa trung bình năm lớn: từ 1500 - 2000 mm/năm.; - Độ ẩm không khí cao, trên 80%.", icon: "bar_chart", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 16, label: "Ve va phan tich bieu do khi hau", short: "Ve PT BD KH", level: TagLevel.VD, group: "Khi hau & thuy van", text: "b) Tính chất ẩm; - Lượng mưa trung bình năm lớn: từ 1500 - 2000 mm/năm.; - Độ ẩm không khí cao, trên 80%.", icon: "legend_toggle", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 17, label: "Vai tro khi hau doi voi du lich", short: "KH-Du lich", level: TagLevel.VD, group: "Khi hau & thuy van", text: "- Đặc điểm:; + Ở miền Bắc: nửa đầu mùa đông thời tiết lạnh khô, nửa sau mùa đông thời tiết lạnh ẩm, có mưa phùn.; + Ở miền Nam, Tín phong chiếm ưu thế đem đến mùa khô cho Nan Bộ và Tây Nguyên, gây mưa cho vùng biển Nam Trung Bộ.", icon: "camera_outdoor", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 18, label: "Ung pho voi bien doi khi hau", short: "Ung pho BDKH", level: TagLevel.VDC, group: "Khi hau & thuy van", text: "+ Nông nghiệp: cung cấp nước cho trồng trọt và chăn nuôi, nuôi trồng, đánh bắt thuỷ sản.; + Công nghiệp: phát triển thuỷ điện, cung cấp nước cho các ngành công nghiệp.; + Dịch vụ: có giá trị về giao thông, phát triển du lịch.", icon: "verified", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 19, label: "Khai thac tong hop tai nguyen nuoc", short: "Khai thac nuoc", level: TagLevel.VDC, group: "Khi hau & thuy van", text: "- Đối với sinh hoạt: là nguồn nước quan trọng phục vụ cho sinh hoạt của người dân.; 3. VAI TRÒ CỦA TÀI NGUYÊN KHÍ HẬU VÀ TÀI NGUYÊN NƯỚC ĐỐI VỚI SỰ PHÁT TRIỂN KINH TẾ-XÃ HỘI CỦA NƯỚC TA; 3.1. Ảnh hưởng của khí hậu đối với sản xuất nông nghiệp", icon: "water_damage", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 20, label: "Tac dong bien doi khi hau toi tu nhien", short: "BDKH TN", level: TagLevel.VDC, group: "Khi hau & thuy van", text: "- Khó khăn:; + Nhiều thiên tai thường xuyên xảy ra (bão, lũ lụt, hạn hán, gió Tây khô nóng, sương muối,...) gây thiệt hại cho sản xuất nông nghiệp.; + Khí hậu nóng ẩm tạo điều kiện cho sâu bệnh, dịch bệnh, nấm mốc phát triển gây hại cho cây trồng, vật nuôi.", icon: "warning", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 21, label: "Ba nhom dat chinh", short: "Ba nhom dat", level: TagLevel.NB, group: "Tho nhuong & sinh vat", text: "CHỦ ĐỀ 3: THỔ NHƯỠNG VÀ SINH VẬT VIỆT NAM; 1. THỔ NHƯỠNG VIỆT NAM; 1.1. Tính chất nhiệt đới gió mùa của lớp phủ thổ nhưỡng", icon: "potted_plant", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 22, label: "Tinh chat nhiet doi gio mua cua tho nhuong", short: "Tho NDGM", level: TagLevel.TH, group: "Tho nhuong & sinh vat", text: "1. THỔ NHƯỠNG VIỆT NAM; 1.1. Tính chất nhiệt đới gió mùa của lớp phủ thổ nhưỡng; - Thổ nhưỡng là lớp vật chất mỏng, vụn bở, bao phủ trên bề mặt các lục địa và đảo, được đặc trưng bởi độ phì.", icon: "eco", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 23, label: "Dat feralit va gia tri su dung", short: "Dat feralit", level: TagLevel.TH, group: "Tho nhuong & sinh vat", text: "- Đặc điểm:; + Chứa nhiều oxít sắt và oxít nhôm tạo nên màu đỏ vàng.; + Có lớp vỏ phong hóa dày thoáng khí, dễ thoát nước, đất chua, nghèo các chất badơ và mùn.", icon: "park", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 24, label: "Dat phu sa va gia tri su dung", short: "Dat phu sa", level: TagLevel.TH, group: "Tho nhuong & sinh vat", text: "+ Trong nông nghiệp: sản xuất lương thực, cây công nghiệp hàng năm và cây ăn quả.; + Trong thủy sản: vùng đất phèn, đất mặn tạo điều kiện thuận lợi cho việc đánh bắt thuỷ sản. Ở các rừng ngập mặn ven biển, các bãi triều ngập nước và ở cửa sông lớn thuận lợi cho nuôi trồng thủy sản.; c) Nhóm đất mùn trên núi", icon: "grass", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 25, label: "Su da dang sinh vat Viet Nam", short: "Sinh vat da dang", level: TagLevel.TH, group: "Tho nhuong & sinh vat", text: "CHỦ ĐỀ 3: THỔ NHƯỠNG VÀ SINH VẬT VIỆT NAM; 1. THỔ NHƯỠNG VIỆT NAM; 1.1. Tính chất nhiệt đới gió mùa của lớp phủ thổ nhưỡng", icon: "pets", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 26, label: "Chong thoai hoa dat", short: "Chong thoai hoa", level: TagLevel.VD, group: "Tho nhuong & sinh vat", text: "+ Ở khu vực nhiệt đới ẩm gió mùa, quá trình phong hoá diễn ra với cường độ mạnh.; + Lượng mưa tập trung theo mùa rửa trôi các chất badơ dễ tan đồng thời tích tụ oxit sắt và oxit nhôm.; + Một số nơi mất đi lớp phủ thực vật.", icon: "compost", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 27, label: "Bao ton da dang sinh hoc", short: "Bao ton DDSH", level: TagLevel.VD, group: "Tho nhuong & sinh vat", text: "* Đa dạng về thành phần loài: Ở nước ta đã phát hiện hơn 50.000 loài sinh vật, trong đó nhiều loài thực vật quý hiếm (trầm hương, trắc, sâm Ngọc Linh, nghiến, gỗ gụ…) và động vật quý hiếm (Sao la, voi, bò tót, trĩ…).; * Đa dạng về nguồn gen di truyền: số lượng các cá thể trong mỗi loài tương đối phong phú, tạo nên sự đa dạng về nguồn gen di truyền,…; * Đa dạng về hệ sinh thái:", icon: "diversity_3", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 28, label: "Pham vi Bien Dong va vung bien Viet Nam", short: "Pham vi bien", level: TagLevel.NB, group: "Bien dao Viet Nam", text: "1.2. Các vùng biển của Việt Nam ở Biển Đông; - Đường cơ sở để tính chiều rộng lãnh hải VN là đường thẳng gãy khúc, nối liền các điểm từ 0 – A11.; - Vùng biển nước ta có diện tích khoàng 1 triệu km2.", icon: "explore", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 29, label: "Dac diem tu nhien vung bien dao", short: "Tu nhien bien", level: TagLevel.NB, group: "Bien dao Viet Nam", text: "- Thiên tai: bão, lốc, áp thấp nhiệt đới,...; c) Hải văn; - Độ muối trung bình là 32 - 33%0.", icon: "waves", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 30, label: "Tai nguyen bien va them luc dia", short: "Tai nguyen bien", level: TagLevel.NB, group: "Bien dao Viet Nam", text: "c) Hải văn; - Độ muối trung bình là 32 - 33%0.; - Dòng biển: thay đổi theo mùa: mùa đông, dòng biển có hướng đông bắc - tây nam; mùa hạ, là tây nam - đông bắc.", icon: "sailing", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 31, label: "Moi truong bien dao Viet Nam", short: "Moi truong bien", level: TagLevel.TH, group: "Bien dao Viet Nam", text: "2. MÔI TRƯỜNG VÀ TÀI NGUYÊN BIỂN ĐẢO VIỆT NAM; 2.1. Môi trường biển đảo Việt Nam; a) Đặc điêm môi trường biển đảo", icon: "recycling", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 32, label: "Luat bien va cac vung bien Viet Nam", short: "Luat bien", level: TagLevel.VD, group: "Bien dao Viet Nam", text: "1.2. Các vùng biển của Việt Nam ở Biển Đông; - Đường cơ sở để tính chiều rộng lãnh hải VN là đường thẳng gãy khúc, nối liền các điểm từ 0 – A11.; - Vùng biển nước ta có diện tích khoàng 1 triệu km2.", icon: "gavel", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 33, label: "Thuan loi, kho khan kinh te bien va bao ve chu quyen", short: "TL-KK bien", level: TagLevel.VD, group: "Bien dao Viet Nam", text: "- Vùng thềm lục địa rộng, bằng phẳng ở phía bắc và phía nam, hẹp và sâu ở miền Trung.; - Có nhiểu đảo và quần đảo, trong đó có 2 quần đảo xa bờ là Hoàng Sa và Trường Sa.; b) Khí hậu", icon: "account_balance", color: "#3357FF", mastery: 0, scale: 1.0 },
];

const LOCALIZED_TOPIC_META: Record<number, { label: string; short: string; group: string }> = {
  1: { label: "Vị trí địa lí và phạm vi lãnh thổ", short: "Vị trí - lãnh thổ", group: "Vị trí địa lí và lãnh thổ" },
  2: { label: "Ảnh hưởng của vị trí địa lí", short: "Ảnh hưởng vị trí", group: "Vị trí địa lí và lãnh thổ" },
  3: { label: "Đặc điểm địa hình Việt Nam", short: "Địa hình VN", group: "Địa hình và khoáng sản" },
  4: { label: "Các khu vực địa hình", short: "Khu vực địa hình", group: "Địa hình và khoáng sản" },
  5: { label: "Đặc điểm khoáng sản Việt Nam", short: "Khoáng sản VN", group: "Địa hình và khoáng sản" },
  6: { label: "Phân bố và sử dụng khoáng sản", short: "Sử dụng khoáng sản", group: "Địa hình và khoáng sản" },
  7: { label: "Phân hoá địa hình và tự nhiên", short: "Phân hoá địa hình", group: "Địa hình và khoáng sản" },
  8: { label: "Khí hậu nhiệt đới ẩm gió mùa", short: "Khí hậu gió mùa", group: "Khí hậu và thuỷ văn" },
  9: { label: "Lưu vực sông và hệ thống sông lớn", short: "Hệ thống sông", group: "Khí hậu và thuỷ văn" },
  10: { label: "Phân hoá khí hậu Việt Nam", short: "Phân hoá khí hậu", group: "Khí hậu và thuỷ văn" },
  11: { label: "Tác động biến đổi khí hậu tới khí hậu và thuỷ văn", short: "Tác động BĐKH", group: "Khí hậu và thuỷ văn" },
  12: { label: "Khí hậu và nông nghiệp", short: "Khí hậu - nông nghiệp", group: "Khí hậu và thuỷ văn" },
  13: { label: "Phân tích một hệ thống sông", short: "Phân tích sông", group: "Khí hậu và thuỷ văn" },
  14: { label: "Hồ, đầm và nước ngầm", short: "Hồ đầm - nước ngầm", group: "Khí hậu và thuỷ văn" },
  15: { label: "Đọc biểu đồ khí hậu", short: "Đọc biểu đồ", group: "Khí hậu và thuỷ văn" },
  16: { label: "Vẽ và phân tích biểu đồ khí hậu", short: "Vẽ biểu đồ", group: "Khí hậu và thuỷ văn" },
  17: { label: "Vai trò khí hậu đối với du lịch", short: "Khí hậu - du lịch", group: "Khí hậu và thuỷ văn" },
  18: { label: "Ứng phó với biến đổi khí hậu", short: "Ứng phó BĐKH", group: "Khí hậu và thuỷ văn" },
  19: { label: "Khai thác tổng hợp tài nguyên nước", short: "Tài nguyên nước", group: "Khí hậu và thuỷ văn" },
  20: { label: "Tác động biến đổi khí hậu tới tự nhiên", short: "BĐKH và tự nhiên", group: "Khí hậu và thuỷ văn" },
  21: { label: "Ba nhóm đất chính", short: "Ba nhóm đất", group: "Thổ nhưỡng và sinh vật" },
  22: { label: "Tính chất nhiệt đới gió mùa của thổ nhưỡng", short: "Thổ nhưỡng gió mùa", group: "Thổ nhưỡng và sinh vật" },
  23: { label: "Đất feralit và giá trị sử dụng", short: "Đất feralit", group: "Thổ nhưỡng và sinh vật" },
  24: { label: "Đất phù sa và giá trị sử dụng", short: "Đất phù sa", group: "Thổ nhưỡng và sinh vật" },
  25: { label: "Sự đa dạng sinh vật Việt Nam", short: "Đa dạng sinh vật", group: "Thổ nhưỡng và sinh vật" },
  26: { label: "Chống thoái hoá đất", short: "Chống thoái hoá đất", group: "Thổ nhưỡng và sinh vật" },
  27: { label: "Bảo tồn đa dạng sinh học", short: "Bảo tồn sinh học", group: "Thổ nhưỡng và sinh vật" },
  28: { label: "Phạm vi Biển Đông và vùng biển Việt Nam", short: "Phạm vi biển", group: "Biển đảo Việt Nam" },
  29: { label: "Đặc điểm tự nhiên vùng biển đảo", short: "Tự nhiên biển đảo", group: "Biển đảo Việt Nam" },
  30: { label: "Tài nguyên biển và thềm lục địa", short: "Tài nguyên biển", group: "Biển đảo Việt Nam" },
  31: { label: "Môi trường biển đảo Việt Nam", short: "Môi trường biển", group: "Biển đảo Việt Nam" },
  32: { label: "Luật biển và các vùng biển Việt Nam", short: "Luật biển", group: "Biển đảo Việt Nam" },
  33: { label: "Thuận lợi, khó khăn kinh tế biển và bảo vệ chủ quyền", short: "Kinh tế biển", group: "Biển đảo Việt Nam" },
};

export const MOCK_TOPICS: Topic[] = TOPIC_CATALOG.map((item) => ({
  topic_id: item.id,
  group_id: Array.from(new Set(TOPIC_CATALOG.map(t => LOCALIZED_TOPIC_META[t.id]?.group || t.group))).indexOf(LOCALIZED_TOPIC_META[item.id]?.group || item.group) + 1,
  group_title: LOCALIZED_TOPIC_META[item.id]?.group || item.group,
  tag_level: item.level,
  keyword_label: LOCALIZED_TOPIC_META[item.id]?.label || item.label,
  short_label: LOCALIZED_TOPIC_META[item.id]?.short || item.short,
  full_text: item.text,
  mastery_percent: item.mastery,
  scale: item.scale,
  delta: 0, attempts_count: 0, avg_time_sec: 0,
  competency_scores: { C1: 0, C2: 0, C3: 0, C4: 0 },
  last_attempt_at: null, error_tags: [], pinned: false,
  history_mastery: { day: 0, week: 0, month: 0, three_months: 0 },
  icon: item.icon,
  color: item.color,
  source_file: `Học liệu Dia8Dragon - ${LOCALIZED_TOPIC_META[item.id]?.group || item.group}`,
  source_excerpt: item.text,
  source_readable: true
}));
