import { Topic, TagLevel } from './types';

export const TOPIC_CATALOG = [
  { id: 1, label: "Vi tri dia li va pham vi lanh tho", short: "VTDL-PVLT", level: TagLevel.NB, group: "Vi tri dia li & pham vi lanh tho", text: "+ Việt Nam nằm ở rìa phía đông của bán đảo Đông Dương, gần trung tâm khu vực Đông Nam Á.; + Nước ta nằm ở vị trí nội chí tuyến bán cầu Bắc; trong khu vực châu Á gió mùa; nơi tiếp giáp giữa đất liền và đại dương, liền kề với các vành đai sinh khoáng.; - Hệ tọa độ:", icon: "location_on", color: "#00f5ff", mastery: 0, scale: 1.0 },
  { id: 2, label: "Anh huong vi tri dia li va pham vi lanh tho", short: "AH VTDL", level: TagLevel.TH, group: "Vi tri dia li & pham vi lanh tho", text: "* Vị trí địa lí và lãnh thổ đã quy định đặc điểm cơ bản của thiên nhiên nước ta mang tính chất nhiệt đới ẩm gió mùa, chịu ảnh hưởng sâu sắc của biển và phân hóa đa dạng:; - Khí hậu: một năm có 2 mùa rõ rệt, chịu ảnh hưởng của các cơn bão lớn.; - Sinh vật và đất: hệ sinh thái rừng nhiệt đới gió mùa phát triển trên đất feralit là cảnh quan tiêu biểu.", icon: "explore", color: "#00f5ff", mastery: 0, scale: 1.0 },
  { id: 3, label: "Dac diem dia hinh Viet Nam", short: "Dia hinh VN", level: TagLevel.NB, group: "Dia hinh & khoang san", text: "a) Địa hình đồi núi chiếm ưu thế; - Đồi núi chiếm 3/4 diện tích lãnh thổ.; - Đồng bằng chiếm 1/4 diện tích lãnh thổ.", icon: "terrain", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 4, label: "Cac khu vuc dia hinh", short: "Khu vuc DH", level: TagLevel.NB, group: "Dia hinh & khoang san", text: "a) Địa hình đồi núi; - Khu vực Đông Bắc; + Phạm vi: Nằm ở tả ngạn sông Hồng.", icon: "landscape", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 5, label: "Dac diem khoang san Viet Nam", short: "Dac diem KS", level: TagLevel.TH, group: "Dia hinh & khoang san", text: "- Cơ cấu: Khoáng sản nước ta khá phong phú và đa dạng. Trên lãnh thổ Việt Nam đã thăm dò được hơn 60 loại khoáng sản khác nhau như khoáng sản: năng lượng, kim loại, phi kim loại.; - Quy mô: phần lớn mỏ khoáng sản có trữ lượng trung bình và nhỏ.; - Phân bố: Khoáng sản nước ta phân bố ở nhiều nơi, nhưng tập trung chủ yếu ở miền Bắc, miền Trung và Tây Nguyên.", icon: "diamond", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 6, label: "Phan bo va su dung khoang san", short: "PB-SD KS", level: TagLevel.TH, group: "Dia hinh & khoang san", text: "- Than đá: ở bể than Quảng Ninh.; - Dầu mỏ và khí tự nhiên: ở vùng thềm lục địa phía đông nam.; - Bô-xít: ở Tây Nguyên (Lâm Đồng, Gia Lai, Kon Tum,...), ngoài ra còn có ở một số tỉnh phía bắc như Lạng Sơn, Cao Bằng, Hà Giang (nay thuộc Tuyên Quang),....", icon: "precision_manufacturing", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 7, label: "Phan hoa dia hinh va tu nhien", short: "Phan hoa DH", level: TagLevel.VD, group: "Dia hinh & khoang san", text: "a) Đối với phân hoá tự nhiên; - Theo độ cao: chia thành 3 vòng đai: nhiệt đới gió mùa, cận nhiệt đới gió mùa trên núi, ôn đới gió mùa trên núi.; - Theo hướng sườn:", icon: "layers", color: "#6366f1", mastery: 0, scale: 1.0 },
  { id: 8, label: "Khi hau nhiet doi am gio mua", short: "KH NDAGM", level: TagLevel.NB, group: "Khi hau & thuy van", text: "a) Tính chất nhiệt đới; - Nhiệt độ trung bình năm trên 200C (trừ vùng núi cao) và tăng dần từ Bắc vào Nam.; - Số giờ nắng nhiều, đạt từ 1400 - 3000 giờ/năm.", icon: "thermostat", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 9, label: "Luu vuc song va he thong song lon", short: "Luu vuc song", level: TagLevel.NB, group: "Khi hau & thuy van", text: "a) Đặc điểm chung; - Mạng lưới sông ngòi dày đặc phân bố rộng khắp trên cả nước: Nước ta có 2360 con sông dài trên 10km.; - Sông chảy theo hai hướng chính là tây bắc - đông nam và vòng cung.", icon: "water", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 10, label: "Phan hoa khi hau Viet Nam", short: "Phan hoa KH", level: TagLevel.TH, group: "Khi hau & thuy van", text: "a) Phân hoá theo chiều bắc-nam; - Miền khí hậu phía Bắc: nhiệt độ trung bình năm trên 200C, có mùa đông lạnh, ít mưa; mùa hạ nóng, ẩm và mưa nhiều.; - Miền khí hậu phía Nam: nhiệt độ trung bình năm trên 250C, có 2 mùa mưa, khô phân hóa rõ rệt.", icon: "wb_sunny", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 11, label: "Tac dong bien doi khi hau toi khi hau va thuy van", short: "BDKH KH-TV", level: TagLevel.TH, group: "Khi hau & thuy van", text: "- Biến đổi về nhiệt độ: nhiệt độ trung bình năm có xu thế tăng trên phạm vi cả nước là 0,890C trong thời kì từ 1958 - 2018.; - Biến đổi về lượng mưa: tổng lượng mưa có tính biến động trên phạm vi cả nước.; - Gia tăng các hiện tượng thời tiết cực đoan như: mưa lớn, bão, rét đậm, rét hại…", icon: "cyclone", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 12, label: "Khi hau va nong nghiep", short: "KH-Nong nghiep", level: TagLevel.TH, group: "Khi hau & thuy van", text: "- Thuận lợi:; + Nguồn nhiệt ẩm dồi dào thuận lợi cho cây trồng vật nuôi phát triển quanh năm, tăng vụ, tăng năng suất.; + Khí hậu nước ta có sự phân hoá thuận lợi trồng các loại cây nhiệt đới cho đến một số cây cận nhiệt và ôn đới.", icon: "agriculture", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 13, label: "Phan tich mot he thong song", short: "Mot HT song", level: TagLevel.TH, group: "Khi hau & thuy van", text: "b) Một số hệ thống sông; * Hệ thống sông Hồng; - Đặc điểm mạng lưới sông:", icon: "humidity_mid", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 14, label: "Ho, dam va nuoc ngam", short: "Ho-dam-NN", level: TagLevel.TH, group: "Khi hau & thuy van", text: "- Vai trò đối với sản xuất:; + Nông nghiệp: cung cấp nước cho trồng trọt và chăn nuôi, nuôi trồng, đánh bắt thuỷ sản.; + Công nghiệp: phát triển thuỷ điện, cung cấp nước cho các ngành công nghiệp.", icon: "waves", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 15, label: "Doc bieu do khi hau va tram khi tuong thuy van", short: "Doc BD KH", level: TagLevel.TH, group: "Khi hau & thuy van", text: "a) Tính chất nhiệt đới; - Nhiệt độ trung bình năm trên 200C (trừ vùng núi cao) và tăng dần từ Bắc vào Nam.; - Số giờ nắng nhiều, đạt từ 1400 - 3000 giờ/năm.", icon: "bar_chart", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 16, label: "Ve va phan tich bieu do khi hau", short: "Ve PT BD KH", level: TagLevel.VD, group: "Khi hau & thuy van", text: "a) Tính chất nhiệt đới; - Nhiệt độ trung bình năm trên 200C (trừ vùng núi cao) và tăng dần từ Bắc vào Nam.; - Số giờ nắng nhiều, đạt từ 1400 - 3000 giờ/năm.", icon: "legend_toggle", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 17, label: "Vai tro khi hau doi voi du lich", short: "KH-Du lich", level: TagLevel.VD, group: "Khi hau & thuy van", text: "- Thuận lợi:; + Điều kiện khí hậu có ảnh hưởng đến một số loại hình du lịch như du lịch biển, du lịch nghỉ dưỡng, du lịch khám phá tự nhiên,...; + Khí hậu nhiệt đới ẩm gió mùa, có sự phân hóa theo mùa và theo đai cao ở nước ta đã tác động trực tiếp đến sự hình thành các điểm du lịch, loại hình du lịch, mùa vụ du lịch…", icon: "camera_outdoor", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 18, label: "Ung pho voi bien doi khi hau", short: "Ung pho BDKH", level: TagLevel.VDC, group: "Khi hau & thuy van", text: "- Các giải pháp giảm nhẹ biến đổi khí hậu:; + Sử dụng tiết kiệm năng lượng: tắt điện khi không sử dụng, đi xe đạp...; + Sử dụng các nguồn năng lượng tái tạo: năng lượng mặt trời, gió, sức nước.", icon: "verified", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 19, label: "Khai thac tong hop tai nguyen nuoc", short: "Khai thac nuoc", level: TagLevel.VDC, group: "Khi hau & thuy van", text: "- Có vai trò quan trọng trong sản xuất và sinh hoạt.; - Mang lại hiệu quả kinh tế cao, đáp ứng được nhu cầu sử dụng nước của các ngành kinh tế.; - Hạn chế lãng phí nước và bảo vệ tài nguyên nước, bảo vệ hệ sinh thái ở lưu vực sông.", icon: "water_damage", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 20, label: "Tac dong bien doi khi hau toi tu nhien", short: "BDKH TN", level: TagLevel.VDC, group: "Khi hau & thuy van", text: "- Biến đổi về nhiệt độ: nhiệt độ trung bình năm có xu thế tăng trên phạm vi cả nước là 0,890C trong thời kì từ 1958 - 2018.; - Biến đổi về lượng mưa: tổng lượng mưa có tính biến động trên phạm vi cả nước.; - Gia tăng các hiện tượng thời tiết cực đoan như: mưa lớn, bão, rét đậm, rét hại…", icon: "warning", color: "#00d1ff", mastery: 0, scale: 1.0 },
  { id: 21, label: "Ba nhom dat chinh", short: "Ba nhom dat", level: TagLevel.NB, group: "Tho nhuong & sinh vat", text: "a) Nhóm đất feralit; - Chiếm tới 65% diện tích đất tự nhiên.; - Phân bố ở các tỉnh trung du và miền núi, từ độ cao 1600 đến 1700m trở xuống.", icon: "potted_plant", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 22, label: "Tinh chat nhiet doi gio mua cua tho nhuong", short: "Tho NDGM", level: TagLevel.TH, group: "Tho nhuong & sinh vat", text: "- Thổ nhưỡng là lớp vật chất mỏng, vụn bở, bao phủ trên bề mặt các lục địa và đảo, được đặc trưng bởi độ phì.; - Các nhân tố hình thành đất ở nước ta: đá mẹ, khí hậu, sinh vật, địa hình, thời gian, con người.; - Nguyên nhân:", icon: "eco", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 23, label: "Dat feralit va gia tri su dung", short: "Dat feralit", level: TagLevel.TH, group: "Tho nhuong & sinh vat", text: "a) Nhóm đất feralit; - Chiếm tới 65% diện tích đất tự nhiên.; - Phân bố ở các tỉnh trung du và miền núi, từ độ cao 1600 đến 1700m trở xuống.", icon: "park", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 24, label: "Dat phu sa va gia tri su dung", short: "Dat phu sa", level: TagLevel.TH, group: "Tho nhuong & sinh vat", text: "b) Nhóm đất phù sa; - Chiếm khoảng 24% diện tích đất tự nhiên.; - Phân bố chủ yếu ở đồng bằng sông Hồng, đồng bằng sông Cửu Long và các đồng bằng duyên hải miền Trung.", icon: "grass", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 25, label: "Su da dang sinh vat Viet Nam", short: "Sinh vat da dang", level: TagLevel.TH, group: "Tho nhuong & sinh vat", text: "* Đa dạng về thành phần loài: Ở nước ta đã phát hiện hơn 50.000 loài sinh vật, trong đó nhiều loài thực vật quý hiếm (trầm hương, trắc, sâm Ngọc Linh, nghiến, gỗ gụ…) và động vật quý hiếm (Sao la, voi, bò tót, trĩ…).; * Đa dạng về nguồn gen di truyền: số lượng các cá thể trong mỗi loài tương đối phong phú, tạo nên sự đa dạng về nguồn gen di truyền,…; * Đa dạng về hệ sinh thái:", icon: "pets", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 26, label: "Chong thoai hoa dat", short: "Chong thoai hoa", level: TagLevel.VD, group: "Tho nhuong & sinh vat", text: "- Thực trạng:; + Nhiều diện tích đất ở trung du và miền núi bị rửa trôi, xói mòn, bạc màu, trở nên khô cằn, nghèo dinh dưỡng; nguy cơ hoang mạc hoá có thể xảy ra ở khu vực duyên hải Nam Trung Bộ.; + Đất ở nhiều vùng cửa sông, ven biển bị suy thoái do nhiễm mặn, nhiễm phèn, ngập úng và có xu hướng ngày càng tăng.", icon: "compost", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 27, label: "Bao ton da dang sinh hoc", short: "Bao ton DDSH", level: TagLevel.VD, group: "Tho nhuong & sinh vat", text: "* Đa dạng sinh học ở nước ta đang bị suy giảm; - Suy giảm số lượng cá thể, loài sinh vật: nhiều loài động, thực vật có nguy cơ bị tuyệt chủng.; - Suy giảm về hệ sinh thái: các hệ sinh thái rừng nguyên sinh bị phá hoại gần hết.", icon: "diversity_3", color: "#00ff88", mastery: 0, scale: 1.0 },
  { id: 28, label: "Pham vi Bien Dong va vung bien Viet Nam", short: "Pham vi bien", level: TagLevel.NB, group: "Bien dao Viet Nam", text: "- Biển Đông thuộc Thái Bình Dương, có diện tích khoảng 3,44 triệu km2, trải rộng từ vĩ độ 30N đến vĩ độ 260B và từ kinh độ 1000 Đ đến 1210Đ.; - Vùng biển VN là một phần của Biển Đông, có diện tích khoảng 1 triệu km2.; - Các nước có chung Biển Đông với Việt Nam là: Trung Quốc, Phi-lip-pin, In-đô-nê-xia, Bờ-ru-nây, Ma-lay-xia, Xing-ga-po, Thái Lan, Cam-pu-chia.", icon: "explore", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 29, label: "Dac diem tu nhien vung bien dao", short: "Tu nhien bien", level: TagLevel.NB, group: "Bien dao Viet Nam", text: "a) Địa hình; - Địa hình ven biển rất đa dạng, bao gồm: vịnh cửa sông, bờ biển mài mòn, tam giác châu, các bãi cát phẳng, cồn cát, đầm phá, vũng vịnh nước sâu,...; - Vùng thềm lục địa rộng, bằng phẳng ở phía bắc và phía nam, hẹp và sâu ở miền Trung.", icon: "waves", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 30, label: "Tai nguyen bien va them luc dia", short: "Tai nguyen bien", level: TagLevel.NB, group: "Bien dao Viet Nam", text: "- Thực vật: Vùng triều ven bờ có nhiều loài rong biển (có hơn 600 loài rong biển, khoảng 400 loài tảo biển cùng nhiều loài cỏ biển có giá trị); - Động vật: có hơn 2000 loài cá, trong đó có khoảng 110 loài có giá trị kinh tế cao. Các loài động vật giáp xác, thân mềm, nhiều loài có giá trị dinh dưỡng cao: tôm, mực, hải sâm,...; - Dầu mỏ và khí tự nhiên: tập trung ở các bể (bồn trũng) trong vùng thềm lục địa", icon: "sailing", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 31, label: "Moi truong bien dao Viet Nam", short: "Moi truong bien", level: TagLevel.TH, group: "Bien dao Viet Nam", text: "a) Đặc điêm môi trường biển đảo; - Môi trường biển đảo là một bộ phận của môi trường sống.; - Đặc điểm :", icon: "recycling", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 32, label: "Luat bien va cac vung bien Viet Nam", short: "Luat bien", level: TagLevel.VD, group: "Bien dao Viet Nam", text: "- Đường cơ sở để tính chiều rộng lãnh hải VN là đường thẳng gãy khúc, nối liền các điểm từ 0 – A11.; - Vùng biển nước ta có diện tích khoàng 1 triệu km2.; - Nội thuỷ là vùng nước tiếp giáp với bờ biển, ở phía trong đường cơ sở và là bộ phận lãnh thổ của Việt Nam.", icon: "gavel", color: "#3357FF", mastery: 0, scale: 1.0 },
  { id: 33, label: "Thuan loi, kho khan kinh te bien va bao ve chu quyen", short: "TL-KK bien", level: TagLevel.VD, group: "Bien dao Viet Nam", text: "b) Vấn đề bảo vệ môi trường biển đảo Việt Nam; * Vai trò : biển đảo có vai trò phát triển kinh tế và bảo vệ tổ quốc.; * Thực trạng :", icon: "account_balance", color: "#3357FF", mastery: 0, scale: 1.0 },
];

const LOCALIZED_TOPIC_META: Record<number, { label: string; short: string; group: string }> = {
  1: { label: "Vị trí địa lí và phạm vi lãnh thổ", short: "Vị trí - lãnh thổ", group: "Vị trí địa lí và lãnh thổ" },
  2: { label: "Ảnh hưởng của vị trí địa lí", short: "Ảnh hưởng vị trí", group: "Vị trí địa lí và lãnh thổ" },
  3: { label: "Đặc điểm địa hình Việt Nam", short: "Địa hình VN", group: "Địa hình và khoáng sản" },
  4: { label: "Các khu vực địa hình", short: "Khu vực địa hình", group: "Địa hình và khoáng sản" },
  5: { label: "Đặc điểm khoáng sản Việt Nam", short: "Khoáng sản VN", group: "Địa hình và khoáng sản" },
  6: { label: "Phân bố và sử dụng khoáng sản", short: "Sử dụng khoáng sản", group: "Địa hình và khoáng sản" },
  7: { label: "Phân hoá địa hình và tự nhiên", short: "Phân hoá địa hình", group: "Địa hình và khoáng sản" },
  8: { label: "Khí hậu nhiệt đới ẩm gió mùa", short: "Khí hậu gió mùa", group: "Khí hậu và thuỷ văn" },
  9: { label: "Lưu vực sông và hệ thống sông lớn", short: "Hệ thống sông", group: "Khí hậu và thuỷ văn" },
  10: { label: "Phân hoá khí hậu Việt Nam", short: "Phân hoá khí hậu", group: "Khí hậu và thuỷ văn" },
  11: { label: "Tác động biến đổi khí hậu tới khí hậu và thuỷ văn", short: "Tác động BĐKH", group: "Khí hậu và thuỷ văn" },
  12: { label: "Khí hậu và nông nghiệp", short: "Khí hậu - nông nghiệp", group: "Khí hậu và thuỷ văn" },
  13: { label: "Phân tích một hệ thống sông", short: "Phân tích sông", group: "Khí hậu và thuỷ văn" },
  14: { label: "Hồ, đầm và nước ngầm", short: "Hồ đầm - nước ngầm", group: "Khí hậu và thuỷ văn" },
  15: { label: "Đọc biểu đồ khí hậu", short: "Đọc biểu đồ", group: "Khí hậu và thuỷ văn" },
  16: { label: "Vẽ và phân tích biểu đồ khí hậu", short: "Vẽ biểu đồ", group: "Khí hậu và thuỷ văn" },
  17: { label: "Vai trò khí hậu đối với du lịch", short: "Khí hậu - du lịch", group: "Khí hậu và thuỷ văn" },
  18: { label: "Ứng phó với biến đổi khí hậu", short: "Ứng phó BĐKH", group: "Khí hậu và thuỷ văn" },
  19: { label: "Khai thác tổng hợp tài nguyên nước", short: "Tài nguyên nước", group: "Khí hậu và thuỷ văn" },
  20: { label: "Tác động biến đổi khí hậu tới tự nhiên", short: "BĐKH và tự nhiên", group: "Khí hậu và thuỷ văn" },
  21: { label: "Ba nhóm đất chính", short: "Ba nhóm đất", group: "Thổ nhưỡng và sinh vật" },
  22: { label: "Tính chất nhiệt đới gió mùa của thổ nhưỡng", short: "Thổ nhưỡng gió mùa", group: "Thổ nhưỡng và sinh vật" },
  23: { label: "Đất feralit và giá trị sử dụng", short: "Đất feralit", group: "Thổ nhưỡng và sinh vật" },
  24: { label: "Đất phù sa và giá trị sử dụng", short: "Đất phù sa", group: "Thổ nhưỡng và sinh vật" },
  25: { label: "Sự đa dạng sinh vật Việt Nam", short: "Đa dạng sinh vật", group: "Thổ nhưỡng và sinh vật" },
  26: { label: "Chống thoái hoá đất", short: "Chống thoái hoá đất", group: "Thổ nhưỡng và sinh vật" },
  27: { label: "Bảo tồn đa dạng sinh học", short: "Bảo tồn sinh học", group: "Thổ nhưỡng và sinh vật" },
  28: { label: "Phạm vi Biển Đông và vùng biển Việt Nam", short: "Phạm vi biển", group: "Biển đảo Việt Nam" },
  29: { label: "Đặc điểm tự nhiên vùng biển đảo", short: "Tự nhiên biển đảo", group: "Biển đảo Việt Nam" },
  30: { label: "Tài nguyên biển và thềm lục địa", short: "Tài nguyên biển", group: "Biển đảo Việt Nam" },
  31: { label: "Môi trường biển đảo Việt Nam", short: "Môi trường biển", group: "Biển đảo Việt Nam" },
  32: { label: "Luật biển và các vùng biển Việt Nam", short: "Luật biển", group: "Biển đảo Việt Nam" },
  33: { label: "Thuận lợi, khó khăn kinh tế biển và bảo vệ chủ quyền", short: "Kinh tế biển", group: "Biển đảo Việt Nam" },
};

export const MOCK_TOPICS: Topic[] = TOPIC_CATALOG.map((item) => ({
  topic_id: item.id,
  group_id: Array.from(new Set(TOPIC_CATALOG.map(t => LOCALIZED_TOPIC_META[t.id]?.group || t.group))).indexOf(LOCALIZED_TOPIC_META[item.id]?.group || item.group) + 1,
  group_title: LOCALIZED_TOPIC_META[item.id]?.group || item.group,
  tag_level: item.level,
  keyword_label: LOCALIZED_TOPIC_META[item.id]?.label || item.label,
  short_label: LOCALIZED_TOPIC_META[item.id]?.short || item.short,
  full_text: item.text,
  mastery_percent: item.mastery,
  scale: item.scale,
  delta: 0, attempts_count: 0, avg_time_sec: 0,
  competency_scores: { C1: 0, C2: 0, C3: 0, C4: 0 },
  last_attempt_at: null, error_tags: [], pinned: false,
  history_mastery: { day: 0, week: 0, month: 0, three_months: 0 },
  icon: item.icon,
  color: item.color,
  source_file: `Học liệu Dia8Dragon - ${LOCALIZED_TOPIC_META[item.id]?.group || item.group}`,
  source_excerpt: item.text,
  source_readable: true,
  infographic_url: `/hsg8-infographics/topic-original/${String(item.id).padStart(2, '0')}.jpg`
}));
